[book]
authors = ["Orquestador Soberano"]
language = "en"
src = "src"
title = "Sovereign Developer Portal"

[build]
build-dir = "book"
create-missing = true
use-default-preprocessors = true

[preprocessor]

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
marker = "[[_TOC_]]"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
no-section-label = true
default-theme = "sovereign-light"
preferred-dark-theme = "sovereign-dark"
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[output.html.fold]
enable = true
level = 0

[output.html.redirect]
"display/VST/Main+benefits+of+VST+3/index.html" = "../../../pages/Main+benefits+of+VST+3/index.html"

#[output.linkcheck]
#optional = true
