[book]
authors = ["ascheffler", "nzorn", "ygrabit"]
language = "en"
multilingual = false
src = "src"
title = "VST 3 Developer Portal"
text-direction = "ltr"

[build]
build-dir = "book"
create-missing = true
use-default-preprocessors = true

[preprocessor]

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
marker = "[[_TOC_]]"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
no-section-label = true
default-theme = "steinberg-light"
preferred-dark-theme = "steinberg-dark"
git-repository-url = "https://github.com/steinbergmedia/vst3_dev_portal/tree/deploy"
git-repository-icon = "fa-github"
#edit-url-template = "https://github.com/steinbergmedia/vst3_dev_portal/edit/deploy/{path}"
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[output.html.print]
enable = true    # include support for printable output
page-break = true # insert page-break after each chapter

[output.linkcheck]
optional = true

[output.html.fold]
enable = true
level = 0

[output.html.redirect]
"display/VST/Main+benefits+of+VST+3/index.html" = "../../../pages/Main+benefits+of+VST+3/index.html"
